//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastReporting.UI.WPF.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CastReporting.UI.WPF.Resources.Languages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string btnActiveWS {
            get {
                return ResourceManager.GetString("btnActiveWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string btnAddWS {
            get {
                return ResourceManager.GetString("btnAddWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDeleteWS {
            get {
                return ResourceManager.GetString("btnDeleteWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        public static string btnGenerateReport {
            get {
                return ResourceManager.GetString("btnGenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string btnPingWS {
            get {
                return ResourceManager.GetString("btnPingWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSaveSettings {
            get {
                return ResourceManager.GetString("btnSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © CAST.
        /// </summary>
        public static string lblAboutCopyright {
            get {
                return ResourceManager.GetString("lblAboutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAST - Report Generator .
        /// </summary>
        public static string lblAboutTitle {
            get {
                return ResourceManager.GetString("lblAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string lblAboutVersion {
            get {
                return ResourceManager.GetString("lblAboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lblFieldActiveWS {
            get {
                return ResourceManager.GetString("lblFieldActiveWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good quality.
        /// </summary>
        public static string lblFieldQualityGood {
            get {
                return ResourceManager.GetString("lblFieldQualityGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low quality.
        /// </summary>
        public static string lblFieldQualityLow {
            get {
                return ResourceManager.GetString("lblFieldQualityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium quality.
        /// </summary>
        public static string lblFieldQualityMedium {
            get {
                return ResourceManager.GetString("lblFieldQualityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very low quality.
        /// </summary>
        public static string lblFieldQualityVeryLow {
            get {
                return ResourceManager.GetString("lblFieldQualityVeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size limit large.
        /// </summary>
        public static string lblFieldSizeLimitLarge {
            get {
                return ResourceManager.GetString("lblFieldSizeLimitLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size limit medium.
        /// </summary>
        public static string lblFieldSizeLimitMedium {
            get {
                return ResourceManager.GetString("lblFieldSizeLimitMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size limit small.
        /// </summary>
        public static string lblFieldSizeLimitSmall {
            get {
                return ResourceManager.GetString("lblFieldSizeLimitSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service.
        /// </summary>
        public static string lblFieldUrlWS {
            get {
                return ResourceManager.GetString("lblFieldUrlWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string lblFieldWSLogin {
            get {
                return ResourceManager.GetString("lblFieldWSLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblFieldWSPassword {
            get {
                return ResourceManager.GetString("lblFieldWSPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string lblHeaderApplication {
            get {
                return ResourceManager.GetString("lblHeaderApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string lblHeaderPortfolio {
            get {
                return ResourceManager.GetString("lblHeaderPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string lblItemEnglish {
            get {
                return ResourceManager.GetString("lblItemEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string lblItemFrench {
            get {
                return ResourceManager.GetString("lblItemFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string lblItemSpanish {
            get {
                return ResourceManager.GetString("lblItemSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags Selection.
        /// </summary>
        public static string lblPortfolioCategoriesSelection {
            get {
                return ResourceManager.GetString("lblPortfolioCategoriesSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select application.
        /// </summary>
        public static string lblSelectApplication {
            get {
                return ResourceManager.GetString("lblSelectApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select snapshot.
        /// </summary>
        public static string lblSelectCurrentSnapshot {
            get {
                return ResourceManager.GetString("lblSelectCurrentSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string lblSelectPortfolioCategories {
            get {
                return ResourceManager.GetString("lblSelectPortfolioCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tags.
        /// </summary>
        public static string lblSelectPortfolioTags {
            get {
                return ResourceManager.GetString("lblSelectPortfolioTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select older snapshot.
        /// </summary>
        public static string lblSelectPreviousSnapshot {
            get {
                return ResourceManager.GetString("lblSelectPreviousSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path template.
        /// </summary>
        public static string lblTemplatePath {
            get {
                return ResourceManager.GetString("lblTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application qualities Thresholds (TQI score).
        /// </summary>
        public static string lblTitleApplicationQuality {
            get {
                return ResourceManager.GetString("lblTitleApplicationQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings.
        /// </summary>
        public static string lblTitleApplicationSettings {
            get {
                return ResourceManager.GetString("lblTitleApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application sizes Thresholds (number of code lines).
        /// </summary>
        public static string lblTitleApplicationSize {
            get {
                return ResourceManager.GetString("lblTitleApplicationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Generator.
        /// </summary>
        public static string lblTitleMain {
            get {
                return ResourceManager.GetString("lblTitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service Configuration.
        /// </summary>
        public static string lblTitleManageWS {
            get {
                return ResourceManager.GetString("lblTitleManageWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string lblTitleMessages {
            get {
                return ResourceManager.GetString("lblTitleMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string lblTitleSettings {
            get {
                return ResourceManager.GetString("lblTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot selection.
        /// </summary>
        public static string lblTitleSnapshotSelection {
            get {
                return ResourceManager.GetString("lblTitleSnapshotSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report template selection.
        /// </summary>
        public static string lblTitleTemplateSelection {
            get {
                return ResourceManager.GetString("lblTitleTemplateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string mnuQuit {
            get {
                return ResourceManager.GetString("mnuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string mnuReporting {
            get {
                return ResourceManager.GetString("mnuReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string mnuSettings {
            get {
                return ResourceManager.GetString("mnuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebService Configuration.
        /// </summary>
        public static string mnuWSConfiguration {
            get {
                return ResourceManager.GetString("mnuWSConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report generated successfully !.
        /// </summary>
        public static string msgDocumentGenerationSuccess {
            get {
                return ResourceManager.GetString("msgDocumentGenerationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during execution.
        /// </summary>
        public static string msgGenericError {
            get {
                return ResourceManager.GetString("msgGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web service invalid !.
        /// </summary>
        public static string msgPingServiceFailure {
            get {
                return ResourceManager.GetString("msgPingServiceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web service valid !.
        /// </summary>
        public static string msgPingServiceSuccess {
            get {
                return ResourceManager.GetString("msgPingServiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation proceeded successfully. Click below to see the report :.
        /// </summary>
        public static string msgReportGenerationSuccess {
            get {
                return ResourceManager.GetString("msgReportGenerationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service URL activated successfully !.
        /// </summary>
        public static string msgServiceActivated {
            get {
                return ResourceManager.GetString("msgServiceActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service URL added and activated successfully !.
        /// </summary>
        public static string msgServiceActivatedAddedOK {
            get {
                return ResourceManager.GetString("msgServiceActivatedAddedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Web Service URL already exist..
        /// </summary>
        public static string msgServiceAddedAlreadyExist {
            get {
                return ResourceManager.GetString("msgServiceAddedAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add this Web Service URL. Please enter a valid url as http://&lt;server&gt;:&lt;port&gt;/&lt;war&gt;/rest and valid login/password.
        /// </summary>
        public static string msgServiceAddedFailed {
            get {
                return ResourceManager.GetString("msgServiceAddedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service URL added successfully !.
        /// </summary>
        public static string msgServiceAddedOK {
            get {
                return ResourceManager.GetString("msgServiceAddedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service URL removed  successfully !.
        /// </summary>
        public static string msgServiceRemoved {
            get {
                return ResourceManager.GetString("msgServiceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        public static string msgSettingsSaved {
            get {
                return ResourceManager.GetString("msgSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred during web service requesting.
        /// </summary>
        public static string msgWSError {
            get {
                return ResourceManager.GetString("msgWSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear messages..
        /// </summary>
        public static string toolTipClearMsg {
            get {
                return ResourceManager.GetString("toolTipClearMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Directory..
        /// </summary>
        public static string toolTipOpenDirectory {
            get {
                return ResourceManager.GetString("toolTipOpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the template list..
        /// </summary>
        public static string toolTipRefreshTemplate {
            get {
                return ResourceManager.GetString("toolTipRefreshTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can double click on any template to open the related file. Therefore, you will be able to edit the template..
        /// </summary>
        public static string toolTipTemplateLb {
            get {
                return ResourceManager.GetString("toolTipTemplateLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid WebService url as http://&lt;server&gt;:&lt;port&gt;/&lt;war&gt;/rest.
        /// </summary>
        public static string toolTipUrlWs {
            get {
                return ResourceManager.GetString("toolTipUrlWs", resourceCulture);
            }
        }
    }
}
