//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastReporting.UI.WPF.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CastReporting.UI.WPF.Resources.Languages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active.
        /// </summary>
        public static string btnActiveWS {
            get {
                return ResourceManager.GetString("btnActiveWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validate.
        /// </summary>
        public static string btnAddWS {
            get {
                return ResourceManager.GetString("btnAddWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string btnDeleteWS {
            get {
                return ResourceManager.GetString("btnDeleteWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate Report.
        /// </summary>
        public static string btnGenerateReport {
            get {
                return ResourceManager.GetString("btnGenerateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test.
        /// </summary>
        public static string btnPingWS {
            get {
                return ResourceManager.GetString("btnPingWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string btnSaveSettings {
            get {
                return ResourceManager.GetString("btnSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copyright © CAST.
        /// </summary>
        public static string lblAboutCopyright {
            get {
                return ResourceManager.GetString("lblAboutCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CAST - Report Generator .
        /// </summary>
        public static string lblAboutTitle {
            get {
                return ResourceManager.GetString("lblAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version {0}.
        /// </summary>
        public static string lblAboutVersion {
            get {
                return ResourceManager.GetString("lblAboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active.
        /// </summary>
        public static string lblFieldActiveWS {
            get {
                return ResourceManager.GetString("lblFieldActiveWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Good quality.
        /// </summary>
        public static string lblFieldQualityGood {
            get {
                return ResourceManager.GetString("lblFieldQualityGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Low quality.
        /// </summary>
        public static string lblFieldQualityLow {
            get {
                return ResourceManager.GetString("lblFieldQualityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Medium quality.
        /// </summary>
        public static string lblFieldQualityMedium {
            get {
                return ResourceManager.GetString("lblFieldQualityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Very low quality.
        /// </summary>
        public static string lblFieldQualityVeryLow {
            get {
                return ResourceManager.GetString("lblFieldQualityVeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size limit large.
        /// </summary>
        public static string lblFieldSizeLimitLarge {
            get {
                return ResourceManager.GetString("lblFieldSizeLimitLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size limit medium.
        /// </summary>
        public static string lblFieldSizeLimitMedium {
            get {
                return ResourceManager.GetString("lblFieldSizeLimitMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size limit small.
        /// </summary>
        public static string lblFieldSizeLimitSmall {
            get {
                return ResourceManager.GetString("lblFieldSizeLimitSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web Service.
        /// </summary>
        public static string lblFieldUrlWS {
            get {
                return ResourceManager.GetString("lblFieldUrlWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User.
        /// </summary>
        public static string lblFieldWSLogin {
            get {
                return ResourceManager.GetString("lblFieldWSLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string lblFieldWSPassword {
            get {
                return ResourceManager.GetString("lblFieldWSPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application.
        /// </summary>
        public static string lblHeaderApplication {
            get {
                return ResourceManager.GetString("lblHeaderApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Portfolio.
        /// </summary>
        public static string lblHeaderPortfolio {
            get {
                return ResourceManager.GetString("lblHeaderPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        public static string lblItemEnglish {
            get {
                return ResourceManager.GetString("lblItemEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        public static string lblItemFrench {
            get {
                return ResourceManager.GetString("lblItemFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spanish.
        /// </summary>
        public static string lblItemSpanish {
            get {
                return ResourceManager.GetString("lblItemSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tag Selection.
        /// </summary>
        public static string lblPortfolioCategoriesSelection {
            get {
                return ResourceManager.GetString("lblPortfolioCategoriesSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select application.
        /// </summary>
        public static string lblSelectApplication {
            get {
                return ResourceManager.GetString("lblSelectApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select snapshot.
        /// </summary>
        public static string lblSelectCurrentSnapshot {
            get {
                return ResourceManager.GetString("lblSelectCurrentSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Category.
        /// </summary>
        public static string lblSelectPortfolioCategories {
            get {
                return ResourceManager.GetString("lblSelectPortfolioCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Tag.
        /// </summary>
        public static string lblSelectPortfolioTags {
            get {
                return ResourceManager.GetString("lblSelectPortfolioTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select older snapshot.
        /// </summary>
        public static string lblSelectPreviousSnapshot {
            get {
                return ResourceManager.GetString("lblSelectPreviousSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path template.
        /// </summary>
        public static string lblTemplatePath {
            get {
                return ResourceManager.GetString("lblTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application qualities Thresholds (TQI score).
        /// </summary>
        public static string lblTitleApplicationQuality {
            get {
                return ResourceManager.GetString("lblTitleApplicationQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application settings.
        /// </summary>
        public static string lblTitleApplicationSettings {
            get {
                return ResourceManager.GetString("lblTitleApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application sizes Thresholds (number of code lines).
        /// </summary>
        public static string lblTitleApplicationSize {
            get {
                return ResourceManager.GetString("lblTitleApplicationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report Generator.
        /// </summary>
        public static string lblTitleMain {
            get {
                return ResourceManager.GetString("lblTitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web Service Configuration.
        /// </summary>
        public static string lblTitleManageWS {
            get {
                return ResourceManager.GetString("lblTitleManageWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Messages.
        /// </summary>
        public static string lblTitleMessages {
            get {
                return ResourceManager.GetString("lblTitleMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string lblTitleSettings {
            get {
                return ResourceManager.GetString("lblTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snapshot selection.
        /// </summary>
        public static string lblTitleSnapshotSelection {
            get {
                return ResourceManager.GetString("lblTitleSnapshotSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report template selection.
        /// </summary>
        public static string lblTitleTemplateSelection {
            get {
                return ResourceManager.GetString("lblTitleTemplateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        public static string mnuQuit {
            get {
                return ResourceManager.GetString("mnuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string mnuReporting {
            get {
                return ResourceManager.GetString("mnuReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string mnuSettings {
            get {
                return ResourceManager.GetString("mnuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WebService Configuration.
        /// </summary>
        public static string mnuWSConfiguration {
            get {
                return ResourceManager.GetString("mnuWSConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report generated successfully !.
        /// </summary>
        public static string msgDocumentGenerationSuccess {
            get {
                return ResourceManager.GetString("msgDocumentGenerationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error Generating Report.
        /// </summary>
        public static string msgErrorGeneratingReport {
            get {
                return ResourceManager.GetString("msgErrorGeneratingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured during execution.
        /// </summary>
        public static string msgGenericError {
            get {
                return ResourceManager.GetString("msgGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web service invalid !.
        /// </summary>
        public static string msgPingServiceFailure {
            get {
                return ResourceManager.GetString("msgPingServiceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web service valid !.
        /// </summary>
        public static string msgPingServiceSuccess {
            get {
                return ResourceManager.GetString("msgPingServiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Typically happens when Portfolio report is generated based on a REST API not connected to measure schema..
        /// </summary>
        public static string msgReportErrorNoAAD {
            get {
                return ResourceManager.GetString("msgReportErrorNoAAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Typically happens when Report Generator does not find REST API.
        /// </summary>
        public static string msgReportErrorNoRestAPI {
            get {
                return ResourceManager.GetString("msgReportErrorNoRestAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generation proceeded successfully. Click below to see the report :.
        /// </summary>
        public static string msgReportGenerationSuccess {
            get {
                return ResourceManager.GetString("msgReportGenerationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web Service URL activated successfully !.
        /// </summary>
        public static string msgServiceActivated {
            get {
                return ResourceManager.GetString("msgServiceActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web Service URL added and activated successfully !.
        /// </summary>
        public static string msgServiceActivatedAddedOK {
            get {
                return ResourceManager.GetString("msgServiceActivatedAddedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This Web Service URL already exist..
        /// </summary>
        public static string msgServiceAddedAlreadyExist {
            get {
                return ResourceManager.GetString("msgServiceAddedAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to add this Web Service URL. Please enter a valid url as http://&lt;server&gt;:&lt;port&gt;/&lt;war&gt;/rest and valid login/password.
        /// </summary>
        public static string msgServiceAddedFailed {
            get {
                return ResourceManager.GetString("msgServiceAddedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web Service URL added successfully !.
        /// </summary>
        public static string msgServiceAddedOK {
            get {
                return ResourceManager.GetString("msgServiceAddedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web Service URL removed  successfully !.
        /// </summary>
        public static string msgServiceRemoved {
            get {
                return ResourceManager.GetString("msgServiceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings saved.
        /// </summary>
        public static string msgSettingsSaved {
            get {
                return ResourceManager.GetString("msgSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error occurred during web service requesting.
        /// </summary>
        public static string msgWSError {
            get {
                return ResourceManager.GetString("msgWSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear messages..
        /// </summary>
        public static string toolTipClearMsg {
            get {
                return ResourceManager.GetString("toolTipClearMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Directory..
        /// </summary>
        public static string toolTipOpenDirectory {
            get {
                return ResourceManager.GetString("toolTipOpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh the template list..
        /// </summary>
        public static string toolTipRefreshTemplate {
            get {
                return ResourceManager.GetString("toolTipRefreshTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can double click on any template to open the related file. Therefore, you will be able to edit the template..
        /// </summary>
        public static string toolTipTemplateLb {
            get {
                return ResourceManager.GetString("toolTipTemplateLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a valid WebService url as http://&lt;server&gt;:&lt;port&gt;/&lt;war&gt;/rest.
        /// </summary>
        public static string toolTipUrlWs {
            get {
                return ResourceManager.GetString("toolTipUrlWs", resourceCulture);
            }
        }
    }
}
