//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastReporting.Reporting.Core.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CastReporting.Reporting.Core.Languages.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Acceptable.
        /// </summary>
        public static string Acceptable {
            get {
                return ResourceManager.GetString("Acceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Achiev..
        /// </summary>
        public static string Achiev {
            get {
                return ResourceManager.GetString("Achiev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Achievement.
        /// </summary>
        public static string Achievement {
            get {
                return ResourceManager.GetString("Achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Achievement ratio.
        /// </summary>
        public static string AchievementRatio {
            get {
                return ResourceManager.GetString("AchievementRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à %.
        /// </summary>
        public static string AchievRatio {
            get {
                return ResourceManager.GetString("AchievRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action Status.
        /// </summary>
        public static string ActionStatus {
            get {
                return ResourceManager.GetString("ActionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added Critical Violations.
        /// </summary>
        public static string AddedCriticalViolations {
            get {
                return ResourceManager.GetString("AddedCriticalViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added Violations.
        /// </summary>
        public static string AddedViolations {
            get {
                return ResourceManager.GetString("AddedViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added Vulnerabilities.
        /// </summary>
        public static string AddedVulnerabilities {
            get {
                return ResourceManager.GetString("AddedVulnerabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Additional information bookmark.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AEP.
        /// </summary>
        public static string AEP {
            get {
                return ResourceManager.GetString("AEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Applications.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arch..
        /// </summary>
        public static string Arch {
            get {
                return ResourceManager.GetString("Arch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Architectural Design.
        /// </summary>
        public static string ArchitecturalDesign {
            get {
                return ResourceManager.GetString("ArchitecturalDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Artifact Name.
        /// </summary>
        public static string ArtifactName {
            get {
                return ResourceManager.GetString("ArtifactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Artifacts.
        /// </summary>
        public static string Artifacts {
            get {
                return ResourceManager.GetString("Artifacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQL Art..
        /// </summary>
        public static string ArtifactsSQL {
            get {
                return ResourceManager.GetString("ArtifactsSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automated Function Points.
        /// </summary>
        public static string AutomatedFP {
            get {
                return ResourceManager.GetString("AutomatedFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backfired Function Points.
        /// </summary>
        public static string BackfiredFP {
            get {
                return ResourceManager.GetString("BackfiredFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poor.
        /// </summary>
        public static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business criterion name.
        /// </summary>
        public static string BusinessCriterionName {
            get {
                return ResourceManager.GetString("BusinessCriterionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CAST Rules.
        /// </summary>
        public static string CASTRules {
            get {
                return ResourceManager.GetString("CASTRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chang..
        /// </summary>
        public static string Chang {
            get {
                return ResourceManager.GetString("Chang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changeability.
        /// </summary>
        public static string Changeability {
            get {
                return ResourceManager.GetString("Changeability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classes.
        /// </summary>
        public static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code Lines.
        /// </summary>
        public static string codeLines {
            get {
                return ResourceManager.GetString("codeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commented Code Lines.
        /// </summary>
        public static string commentedCodeLines {
            get {
                return ResourceManager.GetString("commentedCodeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comment Lines.
        /// </summary>
        public static string commentLines {
            get {
                return ResourceManager.GetString("commentLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CAST Complexity.
        /// </summary>
        public static string Complexity {
            get {
                return ResourceManager.GetString("Complexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complexity.
        /// </summary>
        public static string Complexity1 {
            get {
                return ResourceManager.GetString("Complexity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Average Complexity.
        /// </summary>
        public static string ComplexityAverage {
            get {
                return ResourceManager.GetString("ComplexityAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extreme Complexity.
        /// </summary>
        public static string ComplexityExtreme {
            get {
                return ResourceManager.GetString("ComplexityExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complexity Factor.
        /// </summary>
        public static string ComplexityFactor {
            get {
                return ResourceManager.GetString("ComplexityFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à High Complexity.
        /// </summary>
        public static string ComplexityHigh {
            get {
                return ResourceManager.GetString("ComplexityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à High and Very High Complexity.
        /// </summary>
        public static string ComplexityHighAndVeryHigh {
            get {
                return ResourceManager.GetString("ComplexityHighAndVeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Low Complexity.
        /// </summary>
        public static string ComplexityLow {
            get {
                return ResourceManager.GetString("ComplexityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Very High Complexity.
        /// </summary>
        public static string ComplexityVeryHigh {
            get {
                return ResourceManager.GetString("ComplexityVeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complex Objects.
        /// </summary>
        public static string ComplexObjects {
            get {
                return ResourceManager.GetString("ComplexObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compliance.
        /// </summary>
        public static string Compliance {
            get {
                return ResourceManager.GetString("Compliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compliance Score (%).
        /// </summary>
        public static string ComplianceScorePercent {
            get {
                return ResourceManager.GetString("ComplianceScorePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coupling.
        /// </summary>
        public static string coupling {
            get {
                return ResourceManager.GetString("coupling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coupling.
        /// </summary>
        public static string Coupling1 {
            get {
                return ResourceManager.GetString("Coupling1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Average.
        /// </summary>
        public static string CplxAverage {
            get {
                return ResourceManager.GetString("CplxAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extreme.
        /// </summary>
        public static string CplxExtreme {
            get {
                return ResourceManager.GetString("CplxExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à High.
        /// </summary>
        public static string CplxHigh {
            get {
                return ResourceManager.GetString("CplxHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Low.
        /// </summary>
        public static string CplxLow {
            get {
                return ResourceManager.GetString("CplxLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Very High.
        /// </summary>
        public static string CplxVeryHigh {
            get {
                return ResourceManager.GetString("CplxVeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Critical.
        /// </summary>
        public static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Criticality.
        /// </summary>
        public static string Criticality {
            get {
                return ResourceManager.GetString("Criticality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Period.
        /// </summary>
        public static string CurrentPeriod {
            get {
                return ResourceManager.GetString("CurrentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current score.
        /// </summary>
        public static string CurrentScore {
            get {
                return ResourceManager.GetString("CurrentScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cyclomatic Complexity.
        /// </summary>
        public static string cyclomaticComplexity {
            get {
                return ResourceManager.GetString("cyclomaticComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Debt.
        /// </summary>
        public static string Debt {
            get {
                return ResourceManager.GetString("Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Debt Added.
        /// </summary>
        public static string DebtAdded {
            get {
                return ResourceManager.GetString("DebtAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Debt Removed.
        /// </summary>
        public static string DebtRemoved {
            get {
                return ResourceManager.GetString("DebtRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decision Points (total CC).
        /// </summary>
        public static string DecisionP {
            get {
                return ResourceManager.GetString("DecisionP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Defect.
        /// </summary>
        public static string Defect {
            get {
                return ResourceManager.GetString("Defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Delivery (new and modified).
        /// </summary>
        public static string DeliveryLast {
            get {
                return ResourceManager.GetString("DeliveryLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entire Application (whole code).
        /// </summary>
        public static string DeliveryWhole {
            get {
                return ResourceManager.GetString("DeliveryWhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Distinct Operands.
        /// </summary>
        public static string distinctOperands {
            get {
                return ResourceManager.GetString("distinctOperands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Distinct Operators.
        /// </summary>
        public static string distinctOperators {
            get {
                return ResourceManager.GetString("distinctOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Doc..
        /// </summary>
        public static string Doc {
            get {
                return ResourceManager.GetString("Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Efcy.
        /// </summary>
        public static string Efcy {
            get {
                return ResourceManager.GetString("Efcy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Efficiency.
        /// </summary>
        public static string Efficiency {
            get {
                return ResourceManager.GetString("Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effort complexity.
        /// </summary>
        public static string EffortComplexity {
            get {
                return ResourceManager.GetString("EffortComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Equivalence ratio.
        /// </summary>
        public static string EquivalenceRatio {
            get {
                return ResourceManager.GetString("EquivalenceRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Essential Complexity.
        /// </summary>
        public static string essentialComplexity {
            get {
                return ResourceManager.GetString("essentialComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evol..
        /// </summary>
        public static string Evol {
            get {
                return ResourceManager.GetString("Evol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à % Evol..
        /// </summary>
        public static string EvolPercent {
            get {
                return ResourceManager.GetString("EvolPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evolution.
        /// </summary>
        public static string Evolution {
            get {
                return ResourceManager.GetString("Evolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à % Evolution.
        /// </summary>
        public static string EvolutionPercent {
            get {
                return ResourceManager.GetString("EvolutionPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exclusion Status.
        /// </summary>
        public static string ExclusionStatus {
            get {
                return ResourceManager.GetString("ExclusionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fan-In.
        /// </summary>
        public static string fanIn {
            get {
                return ResourceManager.GetString("fanIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fan-Out.
        /// </summary>
        public static string fanOut {
            get {
                return ResourceManager.GetString("fanOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File path.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MMM dd yyyy.
        /// </summary>
        public static string FORMAT_LONG_DATE {
            get {
                return ResourceManager.GetString("FORMAT_LONG_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MM/dd/yyyy.
        /// </summary>
        public static string FORMAT_SHORT_DATE {
            get {
                return ResourceManager.GetString("FORMAT_SHORT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Function Name.
        /// </summary>
        public static string FunctionName {
            get {
                return ResourceManager.GetString("FunctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Good.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grade Evolution.
        /// </summary>
        public static string GradeEvolution {
            get {
                return ResourceManager.GetString("GradeEvolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Granularity.
        /// </summary>
        public static string Granularity {
            get {
                return ResourceManager.GetString("Granularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Halstead Program Length.
        /// </summary>
        public static string halsteadProgramLength {
            get {
                return ResourceManager.GetString("halsteadProgramLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Halstead Program Vocabulary.
        /// </summary>
        public static string halsteadProgramVocabulary {
            get {
                return ResourceManager.GetString("halsteadProgramVocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Halstead Volume.
        /// </summary>
        public static string halsteadVolume {
            get {
                return ResourceManager.GetString("halsteadVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Element Type.
        /// </summary>
        public static string IFPUG_ElementType {
            get {
                return ResourceManager.GetString("IFPUG_ElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FP Details.
        /// </summary>
        public static string IFPUG_FPDetails {
            get {
                return ResourceManager.GetString("IFPUG_FPDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # of FPs.
        /// </summary>
        public static string IFPUG_NoOfFPs {
            get {
                return ResourceManager.GetString("IFPUG_NoOfFPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object Type.
        /// </summary>
        public static string IFPUG_ObjectType {
            get {
                return ResourceManager.GetString("IFPUG_ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Integration Complexity.
        /// </summary>
        public static string integrationComplexity {
            get {
                return ResourceManager.GetString("integrationComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à kLoC.
        /// </summary>
        public static string kLoC {
            get {
                return ResourceManager.GetString("kLoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lack of comments.
        /// </summary>
        public static string LackOfComments {
            get {
                return ResourceManager.GetString("LackOfComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last Updated.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LoC.
        /// </summary>
        public static string LoC {
            get {
                return ResourceManager.GetString("LoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current LoC.
        /// </summary>
        public static string LoCCurrent {
            get {
                return ResourceManager.GetString("LoCCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous LoC.
        /// </summary>
        public static string LoCPrevious {
            get {
                return ResourceManager.GetString("LoCPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Metrics.
        /// </summary>
        public static string Metrics {
            get {
                return ResourceManager.GetString("Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module Name.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Module not found in this application..
        /// </summary>
        public static string ModuleNotFound {
            get {
                return ResourceManager.GetString("ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modules.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No bookmark available for this rule.
        /// </summary>
        public static string NoBookmark {
            get {
                return ResourceManager.GetString("NoBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No data found.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No enabled item.
        /// </summary>
        public static string NoItem {
            get {
                return ResourceManager.GetString("NoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous snapshot was not found..
        /// </summary>
        public static string NoPreviousSnapshot {
            get {
                return ResourceManager.GetString("NoPreviousSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No applicable rules for given application.
        /// </summary>
        public static string NoRules {
            get {
                return ResourceManager.GetString("NoRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No snapshot found for this application.
        /// </summary>
        public static string NoSnapshot {
            get {
                return ResourceManager.GetString("NoSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No violation.
        /// </summary>
        public static string NoViolation {
            get {
                return ResourceManager.GetString("NoViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of object updates.
        /// </summary>
        public static string NumberOfObjectUpdates {
            get {
                return ResourceManager.GetString("NumberOfObjectUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Obj..
        /// </summary>
        public static string Obj {
            get {
                return ResourceManager.GetString("Obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object full name.
        /// </summary>
        public static string ObjectFullName {
            get {
                return ResourceManager.GetString("ObjectFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objectives.
        /// </summary>
        public static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object Name.
        /// </summary>
        public static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objects in violation for rule.
        /// </summary>
        public static string ObjectsInViolationForRule {
            get {
                return ResourceManager.GetString("ObjectsInViolationForRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Object Status.
        /// </summary>
        public static string ObjectStatus {
            get {
                return ResourceManager.GetString("ObjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à per File.
        /// </summary>
        public static string PerFile {
            get {
                return ResourceManager.GetString("PerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Periods.
        /// </summary>
        public static string Periods {
            get {
                return ResourceManager.GetString("Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à per kLoC.
        /// </summary>
        public static string PerkLoC {
            get {
                return ResourceManager.GetString("PerkLoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous Period.
        /// </summary>
        public static string PreviousPeriod {
            get {
                return ResourceManager.GetString("PreviousPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous score.
        /// </summary>
        public static string PreviousScore {
            get {
                return ResourceManager.GetString("PreviousScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PRI.
        /// </summary>
        public static string PRI {
            get {
                return ResourceManager.GetString("PRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prog..
        /// </summary>
        public static string Prog {
            get {
                return ResourceManager.GetString("Prog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Programming Practices.
        /// </summary>
        public static string ProgrammingPractices {
            get {
                return ResourceManager.GetString("ProgrammingPractices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Properties are not available. Only following properties are available : .
        /// </summary>
        public static string PropertiesNotAvailable {
            get {
                return ResourceManager.GetString("PropertiesNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à good.
        /// </summary>
        public static string QualityGood {
            get {
                return ResourceManager.GetString("QualityGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à low.
        /// </summary>
        public static string QualityLow {
            get {
                return ResourceManager.GetString("QualityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à medium.
        /// </summary>
        public static string QualityMedium {
            get {
                return ResourceManager.GetString("QualityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à very good.
        /// </summary>
        public static string QualityVeryGood {
            get {
                return ResourceManager.GetString("QualityVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à very low.
        /// </summary>
        public static string QualityVeryLow {
            get {
                return ResourceManager.GetString("QualityVeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Documentation Ratio.
        /// </summary>
        public static string ratioCommentLinesCodeLines {
            get {
                return ResourceManager.GetString("ratioCommentLinesCodeLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rationale.
        /// </summary>
        public static string Rationale {
            get {
                return ResourceManager.GetString("Rationale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remediation.
        /// </summary>
        public static string Remediation {
            get {
                return ResourceManager.GetString("Remediation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Removed Critical Violations.
        /// </summary>
        public static string RemovedCriticalViolations {
            get {
                return ResourceManager.GetString("RemovedCriticalViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Removed Violations.
        /// </summary>
        public static string RemovedViolations {
            get {
                return ResourceManager.GetString("RemovedViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Removed Vulnerabilities.
        /// </summary>
        public static string RemovedVulnerabilities {
            get {
                return ResourceManager.GetString("RemovedVulnerabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Robu..
        /// </summary>
        public static string Robu {
            get {
                return ResourceManager.GetString("Robu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Robustness.
        /// </summary>
        public static string Robustness {
            get {
                return ResourceManager.GetString("Robustness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rule.
        /// </summary>
        public static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rule Name.
        /// </summary>
        public static string RuleName {
            get {
                return ResourceManager.GetString("RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secu..
        /// </summary>
        public static string Secu {
            get {
                return ResourceManager.GetString("Secu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SEI Maintainability.
        /// </summary>
        public static string SEIMaintainability {
            get {
                return ResourceManager.GetString("SEIMaintainability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size (kLoC).
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à large.
        /// </summary>
        public static string SizeL {
            get {
                return ResourceManager.GetString("SizeL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à medium.
        /// </summary>
        public static string SizeM {
            get {
                return ResourceManager.GetString("SizeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à small.
        /// </summary>
        public static string SizeS {
            get {
                return ResourceManager.GetString("SizeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à extra large.
        /// </summary>
        public static string SizeXL {
            get {
                return ResourceManager.GetString("SizeXL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SLA Violations.
        /// </summary>
        public static string SLAViolations {
            get {
                return ResourceManager.GetString("SLAViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snapshot.
        /// </summary>
        public static string Snapshot {
            get {
                return ResourceManager.GetString("Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snapshot Date.
        /// </summary>
        public static string SnapshotDate {
            get {
                return ResourceManager.GetString("SnapshotDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snapshot Label.
        /// </summary>
        public static string SnapshotLabel {
            get {
                return ResourceManager.GetString("SnapshotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current snapshot is not the latest one. No data can be displayed..
        /// </summary>
        public static string SnapshotNotTheLatestOne {
            get {
                return ResourceManager.GetString("SnapshotNotTheLatestOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snapshots.
        /// </summary>
        public static string Snapshots {
            get {
                return ResourceManager.GetString("Snapshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQL Complexity.
        /// </summary>
        public static string SQLComplexity {
            get {
                return ResourceManager.GetString("SQLComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected status not allowed. Allowed status are : added, deleted or updated..
        /// </summary>
        public static string StatusNotAllowed {
            get {
                return ResourceManager.GetString("StatusNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tables.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target score.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technical Criterion.
        /// </summary>
        public static string TechnicalCriterion {
            get {
                return ResourceManager.GetString("TechnicalCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technical criterion name.
        /// </summary>
        public static string TechnicalCriterionName {
            get {
                return ResourceManager.GetString("TechnicalCriterionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technical Debt.
        /// </summary>
        public static string TechnicalDebt {
            get {
                return ResourceManager.GetString("TechnicalDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technical Debt Added.
        /// </summary>
        public static string TechnicalDebtAdded {
            get {
                return ResourceManager.GetString("TechnicalDebtAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technical Debt Removed.
        /// </summary>
        public static string TechnicalDebtRemoved {
            get {
                return ResourceManager.GetString("TechnicalDebtRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Techno.
        /// </summary>
        public static string Techno {
            get {
                return ResourceManager.GetString("Techno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technologies.
        /// </summary>
        public static string Technologies {
            get {
                return ResourceManager.GetString("Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technology.
        /// </summary>
        public static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technology not found in this application..
        /// </summary>
        public static string TechnoNotFound {
            get {
                return ResourceManager.GetString("TechnoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total Checks.
        /// </summary>
        public static string TotalChecks {
            get {
                return ResourceManager.GetString("TotalChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total Critical Violations.
        /// </summary>
        public static string TotalCriticalViolations {
            get {
                return ResourceManager.GetString("TotalCriticalViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total Failed.
        /// </summary>
        public static string TotalFailed {
            get {
                return ResourceManager.GetString("TotalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successful Checks.
        /// </summary>
        public static string TotalOk {
            get {
                return ResourceManager.GetString("TotalOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à % Total.
        /// </summary>
        public static string TotalPercent {
            get {
                return ResourceManager.GetString("TotalPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total Violations.
        /// </summary>
        public static string TotalViolations {
            get {
                return ResourceManager.GetString("TotalViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total Vulnerabilities.
        /// </summary>
        public static string TotalVulnerabilities {
            get {
                return ResourceManager.GetString("TotalVulnerabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TQI.
        /// </summary>
        public static string TQI {
            get {
                return ResourceManager.GetString("TQI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cur. TQI.
        /// </summary>
        public static string TQICur {
            get {
                return ResourceManager.GetString("TQICur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current TQI.
        /// </summary>
        public static string TQICurrent {
            get {
                return ResourceManager.GetString("TQICurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prev. TQI.
        /// </summary>
        public static string TQIPrev {
            get {
                return ResourceManager.GetString("TQIPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous TQI.
        /// </summary>
        public static string TQIPrevious {
            get {
                return ResourceManager.GetString("TQIPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trans..
        /// </summary>
        public static string Trans {
            get {
                return ResourceManager.GetString("Trans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transaction Entry Point.
        /// </summary>
        public static string TransactionEP {
            get {
                return ResourceManager.GetString("TransactionEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transferability.
        /// </summary>
        public static string Transferability {
            get {
                return ResourceManager.GetString("Transferability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TRI.
        /// </summary>
        public static string TRI {
            get {
                return ResourceManager.GetString("TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updated Artifacts.
        /// </summary>
        public static string UpdatedArtifacts {
            get {
                return ResourceManager.GetString("UpdatedArtifacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Var.
        /// </summary>
        public static string Var {
            get {
                return ResourceManager.GetString("Var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Variation.
        /// </summary>
        public static string Variation {
            get {
                return ResourceManager.GetString("Variation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Version.
        /// </summary>
        public static string VersionCurrent {
            get {
                return ResourceManager.GetString("VersionCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous Version.
        /// </summary>
        public static string VersionPrevious {
            get {
                return ResourceManager.GetString("VersionPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Violation.
        /// </summary>
        public static string Violation {
            get {
                return ResourceManager.GetString("Violation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Violation Path.
        /// </summary>
        public static string ViolationPath {
            get {
                return ResourceManager.GetString("ViolationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Violations.
        /// </summary>
        public static string Violations {
            get {
                return ResourceManager.GetString("Violations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added.
        /// </summary>
        public static string ViolationsAdded {
            get {
                return ResourceManager.GetString("ViolationsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # Violations.
        /// </summary>
        public static string ViolationsCount {
            get {
                return ResourceManager.GetString("ViolationsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Critical Violations.
        /// </summary>
        public static string ViolationsCritical {
            get {
                return ResourceManager.GetString("ViolationsCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Violations.
        /// </summary>
        public static string ViolationsCurrent {
            get {
                return ResourceManager.GetString("ViolationsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Violations (#).
        /// </summary>
        public static string ViolationsNew {
            get {
                return ResourceManager.GetString("ViolationsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous Violations.
        /// </summary>
        public static string ViolationsPrevious {
            get {
                return ResourceManager.GetString("ViolationsPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Removed.
        /// </summary>
        public static string ViolationsRemoved {
            get {
                return ResourceManager.GetString("ViolationsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Still Violations (#).
        /// </summary>
        public static string ViolationsStill {
            get {
                return ResourceManager.GetString("ViolationsStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Violation Status.
        /// </summary>
        public static string ViolationStatus {
            get {
                return ResourceManager.GetString("ViolationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # Viol..
        /// </summary>
        public static string ViolCount {
            get {
                return ResourceManager.GetString("ViolCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à With Violations.
        /// </summary>
        public static string WithViolations {
            get {
                return ResourceManager.GetString("WithViolations", resourceCulture);
            }
        }
    }
}
