//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastReporting.Reporting.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CastReporting.Reporting.Languages.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptable.
        /// </summary>
        public static string Acceptable {
            get {
                return ResourceManager.GetString("Acceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achiev..
        /// </summary>
        public static string Achiev {
            get {
                return ResourceManager.GetString("Achiev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement.
        /// </summary>
        public static string Achievement {
            get {
                return ResourceManager.GetString("Achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement ratio.
        /// </summary>
        public static string AchievementRatio {
            get {
                return ResourceManager.GetString("AchievementRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string AchievRatio {
            get {
                return ResourceManager.GetString("AchievRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual score.
        /// </summary>
        public static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arch..
        /// </summary>
        public static string Arch {
            get {
                return ResourceManager.GetString("Arch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architectural Design.
        /// </summary>
        public static string ArchitecturalDesign {
            get {
                return ResourceManager.GetString("ArchitecturalDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact Name.
        /// </summary>
        public static string ArtifactName {
            get {
                return ResourceManager.GetString("ArtifactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifacts.
        /// </summary>
        public static string Artifacts {
            get {
                return ResourceManager.GetString("Artifacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Art..
        /// </summary>
        public static string ArtifactsSQL {
            get {
                return ResourceManager.GetString("ArtifactsSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated Function Points.
        /// </summary>
        public static string AutomatedFP {
            get {
                return ResourceManager.GetString("AutomatedFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backfired Function Points.
        /// </summary>
        public static string BackfiredFP {
            get {
                return ResourceManager.GetString("BackfiredFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor.
        /// </summary>
        public static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business criterion name.
        /// </summary>
        public static string BusinessCriterionName {
            get {
                return ResourceManager.GetString("BusinessCriterionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chang..
        /// </summary>
        public static string Chang {
            get {
                return ResourceManager.GetString("Chang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changeability.
        /// </summary>
        public static string Changeability {
            get {
                return ResourceManager.GetString("Changeability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAST Complexity.
        /// </summary>
        public static string Complexity {
            get {
                return ResourceManager.GetString("Complexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Complexity.
        /// </summary>
        public static string ComplexityAverage {
            get {
                return ResourceManager.GetString("ComplexityAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Complexity.
        /// </summary>
        public static string ComplexityExtreme {
            get {
                return ResourceManager.GetString("ComplexityExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Complexity.
        /// </summary>
        public static string ComplexityHigh {
            get {
                return ResourceManager.GetString("ComplexityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High and Very High Complexity.
        /// </summary>
        public static string ComplexityHighAndVeryHigh {
            get {
                return ResourceManager.GetString("ComplexityHighAndVeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Complexity.
        /// </summary>
        public static string ComplexityLow {
            get {
                return ResourceManager.GetString("ComplexityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very High Complexity.
        /// </summary>
        public static string ComplexityVeryHigh {
            get {
                return ResourceManager.GetString("ComplexityVeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex Objects.
        /// </summary>
        public static string ComplexObjects {
            get {
                return ResourceManager.GetString("ComplexObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance.
        /// </summary>
        public static string Compliance {
            get {
                return ResourceManager.GetString("Compliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string CplxAverage {
            get {
                return ResourceManager.GetString("CplxAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        public static string CplxExtreme {
            get {
                return ResourceManager.GetString("CplxExtreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string CplxHigh {
            get {
                return ResourceManager.GetString("CplxHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string CplxLow {
            get {
                return ResourceManager.GetString("CplxLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very High.
        /// </summary>
        public static string CplxVeryHigh {
            get {
                return ResourceManager.GetString("CplxVeryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string Critical {
            get {
                return ResourceManager.GetString("Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criticality.
        /// </summary>
        public static string Criticality {
            get {
                return ResourceManager.GetString("Criticality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt.
        /// </summary>
        public static string Debt {
            get {
                return ResourceManager.GetString("Debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt Added.
        /// </summary>
        public static string DebtAdded {
            get {
                return ResourceManager.GetString("DebtAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt Removed.
        /// </summary>
        public static string DebtRemoved {
            get {
                return ResourceManager.GetString("DebtRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Points (total CC).
        /// </summary>
        public static string DecisionP {
            get {
                return ResourceManager.GetString("DecisionP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Delivery (new and modified).
        /// </summary>
        public static string DeliveryLast {
            get {
                return ResourceManager.GetString("DeliveryLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire Application (whole code).
        /// </summary>
        public static string DeliveryWhole {
            get {
                return ResourceManager.GetString("DeliveryWhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc..
        /// </summary>
        public static string Doc {
            get {
                return ResourceManager.GetString("Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efcy.
        /// </summary>
        public static string Efcy {
            get {
                return ResourceManager.GetString("Efcy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string Efficiency {
            get {
                return ResourceManager.GetString("Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evol..
        /// </summary>
        public static string Evol {
            get {
                return ResourceManager.GetString("Evol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Evol..
        /// </summary>
        public static string EvolPercent {
            get {
                return ResourceManager.GetString("EvolPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolution.
        /// </summary>
        public static string Evolution {
            get {
                return ResourceManager.GetString("Evolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Evolution.
        /// </summary>
        public static string EvolutionPercent {
            get {
                return ResourceManager.GetString("EvolutionPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd yyyy.
        /// </summary>
        public static string FORMAT_LONG_DATE {
            get {
                return ResourceManager.GetString("FORMAT_LONG_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        public static string FORMAT_SHORT_DATE {
            get {
                return ResourceManager.GetString("FORMAT_SHORT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Evolution.
        /// </summary>
        public static string GradeEvolution {
            get {
                return ResourceManager.GetString("GradeEvolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Type.
        /// </summary>
        public static string IFPUG_ElementType {
            get {
                return ResourceManager.GetString("IFPUG_ElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FP Details.
        /// </summary>
        public static string IFPUG_FPDetails {
            get {
                return ResourceManager.GetString("IFPUG_FPDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of FPs.
        /// </summary>
        public static string IFPUG_NoOfFPs {
            get {
                return ResourceManager.GetString("IFPUG_NoOfFPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Type.
        /// </summary>
        public static string IFPUG_ObjectType {
            get {
                return ResourceManager.GetString("IFPUG_ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kLoC.
        /// </summary>
        public static string kLoC {
            get {
                return ResourceManager.GetString("kLoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoC.
        /// </summary>
        public static string LoC {
            get {
                return ResourceManager.GetString("LoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current LoC.
        /// </summary>
        public static string LoCCurrent {
            get {
                return ResourceManager.GetString("LoCCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous LoC.
        /// </summary>
        public static string LoCPrevious {
            get {
                return ResourceManager.GetString("LoCPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No enabled item.
        /// </summary>
        public static string NoItem {
            get {
                return ResourceManager.GetString("NoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obj..
        /// </summary>
        public static string Obj {
            get {
                return ResourceManager.GetString("Obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives.
        /// </summary>
        public static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Name.
        /// </summary>
        public static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per File.
        /// </summary>
        public static string PerFile {
            get {
                return ResourceManager.GetString("PerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per kLoC.
        /// </summary>
        public static string PerkLoC {
            get {
                return ResourceManager.GetString("PerkLoC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous score.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRI.
        /// </summary>
        public static string PRI {
            get {
                return ResourceManager.GetString("PRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prog..
        /// </summary>
        public static string Prog {
            get {
                return ResourceManager.GetString("Prog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming Practices.
        /// </summary>
        public static string ProgrammingPractices {
            get {
                return ResourceManager.GetString("ProgrammingPractices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to good.
        /// </summary>
        public static string QualityGood {
            get {
                return ResourceManager.GetString("QualityGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low.
        /// </summary>
        public static string QualityLow {
            get {
                return ResourceManager.GetString("QualityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string QualityMedium {
            get {
                return ResourceManager.GetString("QualityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to very good.
        /// </summary>
        public static string QualityVeryGood {
            get {
                return ResourceManager.GetString("QualityVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to very low.
        /// </summary>
        public static string QualityVeryLow {
            get {
                return ResourceManager.GetString("QualityVeryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rationale.
        /// </summary>
        public static string Rationale {
            get {
                return ResourceManager.GetString("Rationale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remediation.
        /// </summary>
        public static string Remediation {
            get {
                return ResourceManager.GetString("Remediation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robu..
        /// </summary>
        public static string Robu {
            get {
                return ResourceManager.GetString("Robu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robustness.
        /// </summary>
        public static string Robustness {
            get {
                return ResourceManager.GetString("Robustness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Name.
        /// </summary>
        public static string RuleName {
            get {
                return ResourceManager.GetString("RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secu..
        /// </summary>
        public static string Secu {
            get {
                return ResourceManager.GetString("Secu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEI Maintainability.
        /// </summary>
        public static string SEIMaintainability {
            get {
                return ResourceManager.GetString("SEIMaintainability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (kLoC).
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to large.
        /// </summary>
        public static string SizeL {
            get {
                return ResourceManager.GetString("SizeL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string SizeM {
            get {
                return ResourceManager.GetString("SizeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to small.
        /// </summary>
        public static string SizeS {
            get {
                return ResourceManager.GetString("SizeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extra large.
        /// </summary>
        public static string SizeXL {
            get {
                return ResourceManager.GetString("SizeXL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLA Violations.
        /// </summary>
        public static string SLAViolations {
            get {
                return ResourceManager.GetString("SLAViolations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        public static string Snapshot {
            get {
                return ResourceManager.GetString("Snapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot Date.
        /// </summary>
        public static string SnapshotDate {
            get {
                return ResourceManager.GetString("SnapshotDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot Label.
        /// </summary>
        public static string SnapshotLabel {
            get {
                return ResourceManager.GetString("SnapshotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target score.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Criterion.
        /// </summary>
        public static string TechnicalCriterion {
            get {
                return ResourceManager.GetString("TechnicalCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical criterion name.
        /// </summary>
        public static string TechnicalCriterionName {
            get {
                return ResourceManager.GetString("TechnicalCriterionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Debt.
        /// </summary>
        public static string TechnicalDebt {
            get {
                return ResourceManager.GetString("TechnicalDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Debt Added.
        /// </summary>
        public static string TechnicalDebtAdded {
            get {
                return ResourceManager.GetString("TechnicalDebtAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Debt Removed.
        /// </summary>
        public static string TechnicalDebtRemoved {
            get {
                return ResourceManager.GetString("TechnicalDebtRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techno.
        /// </summary>
        public static string Techno {
            get {
                return ResourceManager.GetString("Techno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Checks.
        /// </summary>
        public static string TotalChecks {
            get {
                return ResourceManager.GetString("TotalChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Failed.
        /// </summary>
        public static string TotalFailed {
            get {
                return ResourceManager.GetString("TotalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull Checks.
        /// </summary>
        public static string TotalOk {
            get {
                return ResourceManager.GetString("TotalOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Total.
        /// </summary>
        public static string TotalPercent {
            get {
                return ResourceManager.GetString("TotalPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TQI.
        /// </summary>
        public static string TQI {
            get {
                return ResourceManager.GetString("TQI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cur. TQI.
        /// </summary>
        public static string TQICur {
            get {
                return ResourceManager.GetString("TQICur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current TQI.
        /// </summary>
        public static string TQICurrent {
            get {
                return ResourceManager.GetString("TQICurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev. TQI.
        /// </summary>
        public static string TQIPrev {
            get {
                return ResourceManager.GetString("TQIPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous TQI.
        /// </summary>
        public static string TQIPrevious {
            get {
                return ResourceManager.GetString("TQIPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans..
        /// </summary>
        public static string Trans {
            get {
                return ResourceManager.GetString("Trans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Entry Point.
        /// </summary>
        public static string TransactionEP {
            get {
                return ResourceManager.GetString("TransactionEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferability.
        /// </summary>
        public static string Transferability {
            get {
                return ResourceManager.GetString("Transferability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRI.
        /// </summary>
        public static string TRI {
            get {
                return ResourceManager.GetString("TRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Var.
        /// </summary>
        public static string Var {
            get {
                return ResourceManager.GetString("Var", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation.
        /// </summary>
        public static string Variation {
            get {
                return ResourceManager.GetString("Variation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        public static string VersionCurrent {
            get {
                return ResourceManager.GetString("VersionCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Version.
        /// </summary>
        public static string VersionPrevious {
            get {
                return ResourceManager.GetString("VersionPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string ViolationsAdded {
            get {
                return ResourceManager.GetString("ViolationsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Violations.
        /// </summary>
        public static string ViolationsCount {
            get {
                return ResourceManager.GetString("ViolationsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Violations.
        /// </summary>
        public static string ViolationsCritical {
            get {
                return ResourceManager.GetString("ViolationsCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Violations.
        /// </summary>
        public static string ViolationsCurrent {
            get {
                return ResourceManager.GetString("ViolationsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Violations (#).
        /// </summary>
        public static string ViolationsNew {
            get {
                return ResourceManager.GetString("ViolationsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Violations.
        /// </summary>
        public static string ViolationsPrevious {
            get {
                return ResourceManager.GetString("ViolationsPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        public static string ViolationsRemoved {
            get {
                return ResourceManager.GetString("ViolationsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still Violations (#).
        /// </summary>
        public static string ViolationsStill {
            get {
                return ResourceManager.GetString("ViolationsStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Viol..
        /// </summary>
        public static string ViolCount {
            get {
                return ResourceManager.GetString("ViolCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Violations.
        /// </summary>
        public static string WithViolations {
            get {
                return ResourceManager.GetString("WithViolations", resourceCulture);
            }
        }
    }
}
